/* File generated by helper script from https://github.com/zaydabudayyeh/wave_generator
for use with ECE385 course at the University of Illinois at Urbana Champaign */

module square_rom(
input clk,
input logic [11:0] addr1,
input logic [11:0] addr2,
output logic [7:0] q1,
output logic [7:0] q2
);

logic [7:0] rom [4096];
always_ff @(posedge clk) begin
	q1 <= rom[addr1];
	q2 <= rom[addr2];
end
initial begin $readmemh("square.txt", rom); end
endmodule